name: secondrepojob

on: push

jobs:
   FTPuploade:
     runs-on: ubuntu-latest
     steps:
       - run: date

   Removeoldversion:
     needs: FTPuploade
     runs-on: windows-latest
     steps:
      - run: date
      
   killPID:
     needs: Removeoldversion
     runs-on: windows-latest
     steps:
      - run: date

      
